### PR TITLE
Add github workflow to build container images

### PR DESCRIPTION
**Pull request by jesserockz**
This PR adds a workflow to the repo to auto build the container image when commits/merges are made into `main`.

It will push to both GitHub Container Repository and DockerHub with the tag `latest` and the commit sha.

It will build images for the following platforms:
- `linux/amd64`
- `linux/arm64`
- `linux/arm/v7`

This requires two secrets to be set on the repository for push access to DockerHub:
- `DOCKER_USER`
- `DOCKER_PASSWORD`

GitHub container repository access is granted via the `permissions` definition inside the workflow.

### CODE REVIEW

**Comment by iainbullock** [comment]
Another very helpful PR. I will incorporate it over the next few days. Thanks once again

**Comment by iainbullock** [comment]
@jesserockz not sure I understand what this part does, and in particular what permissions should I assign to secrets.GITHUB_TOKEN?

Thanks Iain

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

**Comment by jesserockz** [comment]
@iainbullock The `secrets.GITHUB_TOKEN` is automatically generated on each workflow run and given the permissions as defined in the yaml file itself (read repo and write to packages). YOu don't have to manually do anything or create that secret.

**Comment by jesserockz** [comment]
@iainbullock feel free to message me on [discord](https://discord.com/users/205416954863812609) if you want some real-time messaging and help understanding some of my changes =)

**Pull request merged**
