### PR TITLE
Add debug info

### PR DESCRIPTION
**Pull request by Olen**
Add some more output if the http-requests fail

### CODE REVIEW

**Comment by iainbullock** [comment]
Thanks a lot for this. 

I merged into the #dev branch rather than #main. This helps me test other mods before merging the whole lot into #main and then making a new release (including builds for Dockerhub). If you have any other imminent PRs, let me know and I will wait for these, otherwise I will test and merge into #main this weekend

**Comment by Olen** [comment]
I was considering a PR to merge the two containers, and doing so for the setup (flask app) seems easy enough, but I see it will require patches to the official Tesla Proxy go-app, and I don't have any experience with go, so I abondoned the idea for now.

**Comment by iainbullock** [comment]
Not sure if you are getting rate limited but sending too many commands. If so you might be interested in an associated project I am working on https://github.com/tesla-local-control/tesla_ble_mqtt_docker with some others

**Comment by Olen** [comment]
Thanks.  I looked at the project, I just don't have any way to connect to a BT device close to the car.
Getting it to work through an ESP-home device directly from HA would maybe work.  It would still only work while at home though, so I hope I'll not get rate limited for now...

**Pull request merged**
