### PR TITLE
Added a Cloudflare configuration guide

### PR DESCRIPTION
**Pull request by juchong**
I wrote up a Cloudflare configuration / setup guide that I've confirmed works. Hope this helps!

### CODE REVIEW

**Comment by iainbullock** [comment]
Thanks for this!

**Comment by juchong** [comment]
No problem! You may want to modify the README to point to the Cloudflare instructions. I didn't want to mess with it for this pull request, though :)

**Comment by iainbullock** [comment]
I will update README in the dev branch so it will become part of main on
the next release!

**Comment by iainbullock** [comment]
I updated README.md in both main and dev, thanks for your contribution

**Pull request merged**
